apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ocelot-api-gw
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ocelot-api-gw
    spec:
      containers:
        - image: "salesmodule.azurecr.io/ocelot-api-gw:1.0"
          imagePullPolicy: Always
          name: ocelot-api-gw
          ports:
            - containerPort: 80


        
