apiVersion: v1
kind: Service
metadata:
  name: customers-api-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: customers-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80  