apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sales-module-ingress
  namespace: {{ .Values.namespace }}
  annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/rewrite-target: /
   nginx.ingress.kubernetes.io/add-base-url : "true"
spec:
  rules:
  - http: 
      paths:
      - path: 
        backend:
          serviceName: catalog-api-service
          servicePort: 80
        path: /catalog
      - path: 
        backend:
          serviceName: customers-api-service
          servicePort: 80
        path: /customers
      - path: 
        backend:
          serviceName: ordering-api-service
          servicePort: 80
        path: /ordering
