apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - image: "salesmodule.azurecr.io/catalog-api:1.0"
          imagePullPolicy: Always
          name: catalog-api
          ports:
            - containerPort: 80